def main():
    N = eval(input("Please input a five digit integer number: "))
    e = int(N%10)
    d = int(N//10%10)
    c = int(N//10//10%10)
    b = int(N//10//10//10%10)
    a = int(N//10//10//10//10%10)
    print(a, b, c, d, e)
    print(e, d, c, b, a)
    print()
    print(a)
    print()
    print(b)
    print()
    print(c)
    print()
    print(d)
    print()
    print(e)
    print()
    
main()
